### ISSUE TITLE
hmn

### ISSUE THREAD

**Issue by danjessen** [spf13/spf13-vim#1]
ERROR: Permission to spf13/snipmate-snippets denied to xxx.
fatal: The remote end hung up unexpectedly
Clone of 'git@github.com:spf13/snipmate-snippets.git' into submodule path '.vim/bundle/snipmate-snippets/snippets' failed

**Comment by cobhimself** [comment]
Same error here...

Clone of 'git@github.com:spf13/snipmate-snippets.git' into submodule path '.vim/bundle/snipmate-snippets/snippets' failed

**Comment by spf13** [comment]
I have resolved this issue. You may need to remove the repo and clone again for it to take affect. The problem was it was pointing to a private repo. The correct public address is ''git://github.com/spf13/snipmate-snippets.git' . If you have already cloned the repo, you can change the remote of the submodule and it will work.

**Comment by danjessen** [comment]
ye its not a big issue ... just thought idd mention it :)
