### ISSUE TITLE
Unknown function: neocomplcache#smart_close_popup

### ISSUE THREAD

**Issue by kenips** [spf13/spf13-vim#224]
Upgraded to latest spf13-vim and getting this error periodically. It seems like neocomplete is just not working but I have it bundled. Any idea?

```
Error detected while processing function <SNR>2_my_cr_function:                                                                                      
line    1:
E117: Unknown function: neocomplcache#smart_close_popup
```

**Comment by kenips** [comment]
I think it has to do with this: https://github.com/Shougo/neocomplcache/issues/88, but I don't see spf13-vim with supertab. Maybe another bundle?

**Comment by kew-l** [comment]
I get this now when just hitting the Enter key in Insert mode.

**Comment by kew-l** [comment]
Figured mine out. I had set up a reduced set of spf13_bundle_groups in my .vimrc.bundles.local a few weeks back and had left neocomplache out. I guess everything kept working after I had made that change because I hadn't done an update/BundleClean yet.

**Comment by spf13** [comment]
Ken if this isn't resolved, please reopen. 

If it doesn't work at first, please clear cache (vimviews) and try again.

**Comment by kenips** [comment]
Sorry for not updating this. My issue is the same as @kevinwaddle. Adding neocomplache back to local bundle solves the problem. The question is: should not adding neocomplache be an issue? Maybe there should be some check for not having neocomplache added in the groups or making it mandatory?

**Comment by lukedomanski** [comment]
I agree with @kenips. I explicitly wanted to disable neocomplcache/neosnippet and replace snippet functionality with snipmate, by placing the supported/documented g:spf13_bundle_groups definition in my .vimrc.bundles.local file. The code in .vimrc.bundles performs the following pseudocoded check:

if  snipmate defined in g:spf13_bundle_groups
      setup snipmate bundles
else if neocomplcache defined in g:spf13_bundle_groups
      setup neocomplcache bundles
endif

This implies their usage is mutually exclusive, and if both are selected, snipmate overrides the neocomplcache selection.

It would be nice if we could take advantage of this provided functionality without breaking the rest of the setup. Otherwise the option to turn neocomplcache group off in favor of snipmate group should probably be removed.

In my case I really just want to turn off neocomplcache, it probably doesn't matter whether I use snipmate or neosnippet.
