### ISSUE TITLE
<ESC> inserts 'pumvisible() ? "\" : "\'

### ISSUE THREAD

**Issue by hierynomus** [spf13/spf13-vim#236]
Just updated my spf13-vim installation. When I now type some text in a file, and press <ESC>, the text `pumvisible() ? "\" : "\` appears. What's causing this?

**Comment by litao91** [comment]
It seems that the mapping from 311 to 316 lines are broken. I currently comment those lines out to make vim work properly. They are basically make the pop-up menu behave more like a IDE, which is not useful for me.

**Comment by jaywilliams** [comment]
Same issue here on Mountain Lion.

**Comment by XCMer** [comment]
The autoclose plugin is interfering with the <esc> mapping. Remove it and the problem will be solved. Exact steps here: http://crossplatform.net/dev/vim-spf13-writes-random-characters-when-pressing-escape.html

**Comment by spf13** [comment]
Grr.. Sorry about this. I'll remove the plugin from the repo or fix the
conflict.

**Comment by abhishek77in** [comment]
@XCMer thanks for the fix!

**Comment by spf13** [comment]
Remember to :BundleClean!

**Comment by techwraith** [comment]
I'm not sure if this is related to your fixes for this @spf13 (most likely not, because I still have autoclose disabled), but I'm seeing `^?` getting inserted when I hit the backspace key instead of it doing it's normal behavior.

If you want to see my `.vimrc.local` here it is, everything else is from a fresh pull:

https://github.com/Techwraith/dotfiles/blob/master/vim/.vimrc.local

**Comment by techwraith** [comment]
After more investigation, it looks like autoclose has nothing to do with it.

**Comment by techwraith** [comment]
I feel like an idiot. running `sttd sane` before running vim will do that.

**Comment by abhishek77in** [comment]
@spf13 issue still exists (just made an update)

**Comment by spf13** [comment]
I can't reproduce. Can someone help me reproduce (or outline the exact
steps they took).

Please remember to update to the latest spf13-vim and clear your
cache (~/.vimviews)

## 

Steve Francia
http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13

**Comment by beeblebrox** [comment]
I have a related issue, if it isn't the same.  You don't need to hit <ESC> to get this behavior in my example, just simply navigating with the up and down arrows on the keyboard reproduces this.  I'm using the newest 3.0 head (0834355a4787637687354c7bddcf4e5bcef2fb87).  Here are the steps that seem to reproduce it from a checkout of this commit:
- `rm -rf ~/.vim*`
- `./bootstrap.sh` (The pymode returns an error, I ignore it and hit enter because I don't care about that)
- wait for the install
- Edit the file I have pasted in here.
- use 'i' for inserting text and then hold down the down arrow on the keyboard.  Viola.. a bunch of pumvisible() ? "\" : "\ are inserted.

```
#            Copyright (c) Dean Michael Berris 2010.
# Distributed under the Boost Software License, Version 1.0.
#    (See accompanying file LICENSE_1_0.txt or copy at
#          http://www.boost.org/LICENSE_1_0.txt)

include_directories(${CPP-NETLIB_SOURCE_DIR})

add_subdirectory(uri)
add_subdirectory(http)

if (Boost_FOUND)
    set(
        TESTS
        message_test
        message_transform_test
        utils_thread_pool
        )
    foreach (test ${TESTS})
        if (${CMAKE_CXX_COMPILER_ID} MATCHES GNU)
          set_source_files_properties(${test}.cpp
            PROPERTIES COMPILE_FLAGS " -ftemplate-depth-128 -O3 -finline-functions -Wno-inline -Wall -pedantic -pthread -Wextra -Wno-long-long -pedantic")
        endif()
        add_executable(cpp-netlib-${test} ${test}.cpp)
    add_dependencies(cpp-netlib-${test} cppnetlib-uri)
        target_link_libraries(cpp-netlib-${test} ${Boost_LIBRARIES} ${CMAKE_THREAD_LIBS_INIT} cppnetlib-uri)
        if (OPENSSL_FOUND)
            target_link_libraries(cpp-netlib-${test} ${OPENSSL_LIBRARIES})
        endif()
        set_target_properties(cpp-netlib-${test}
            PROPERTIES RUNTIME_OUTPUT_DIRECTORY ${CPP-NETLIB_BINARY_DIR}/tests)
        add_test(cpp-netlib-${test}
            ${CPP-NETLIB_BINARY_DIR}/tests/cpp-netlib-${test})
    endforeach (test)

endif()
```

**Comment by jaywilliams** [comment]
Also, enabling F12 "pastie" mode can cause this error to pop up when inserting code.

**Comment by jamestomasino** [comment]
Not sure if it helps narrow it down, but I removed HTML-AutoCloseTag, vim-autoclose, and tlib_vim and my problem disappeared. I probably should have removed them one at a time to see which it was. :/

**Comment by seyDoggy** [comment]
For those still having trouble with this (as I was), I found that if you previously managed your bundles with pathogen and happen to have autoclose installed that way, try as you might to resolve this issue, you never will.

What I had to do was nuke it all and start over:

``` sh
cd
rm -rf .vim* .spf13-vim-3
curl http://j.mp/spf13-vim3 -L -o - | sh
```

After which all pumvisible() issues were resolved.

**Comment by robbyoconnor** [comment]
Why was I having this issue?

**Comment by ghost** [comment]
@robbyoconnor : what do you mean by that?

**Comment by robbyoconnor** [comment]
It stopped...I'm not sure what caused this issue....but a clean nuke and reinstall worked.

**Comment by ghost** [comment]
good
