### ISSUE TITLE
Solarized Colorscheme

### ISSUE THREAD

**Issue by helloliu** [spf13/spf13-vim#240]
Hello Steve
I am a new linuxer and I had some problems using solarized 
like  http://stackoverflow.com/questions/7278267/incorrect-colors-with-vim-in-iterm2-using-solarized
in my vim  highlight current line allways becomes light ,but  when I  :set bg=dark    highlight current line becomes black 
not  darkblue  

I have installed solarized for terminal and choose the dark  
I want my vim colors looks under Gvim so what should I do?  Thanks~

**Comment by ScottSolomko** [comment]
There are two "things" you need to consider when running vim within a terminal window (not a gui, gvim).

1) What is the color depth of the terminal window itself and
2) the color depth of the solarized colorscheme

So assuming the objective is to get both of these to run at 256 colors.

Type these commands and post your results:
1. "tput colors". This will report how many colors your terminal is using.
2. "echo $TERM". This will tell you what terminal you are using.
3. "echo $COLORTERM". If you are using a gnome you should see "gnome-terminal"

**Comment by helloliu** [comment]
@ScottSolomko Thanks for your Answer 
I have type these commands in my terminal 
1.    8
2.    xterm
3.    gnome-terminal
so what should I do to solve this problem
I sure  do  my vim's color depth of the solarized colorscheme
but the highlight current line is light   and if  I type  :set bg=dark in vim ,the highlight current line  becomes black not darkbule like gvim

**Comment by ScottSolomko** [comment]
Alright, so now we need to get your terminal to use the 256 colors instead of 8. In order to do that we need to see if you have any 256 color terminals installed. So type:

find /usr/share/terminfo -name "_256_"

Include the double quotes. You should see something like this:

/usr/share/terminfo/x/xnuppc-256x96
/usr/share/terminfo/x/xnuppc-256x96-m
/usr/share/terminfo/x/xterm+256color
/usr/share/terminfo/x/xnuppc+256x96
/usr/share/terminfo/s/screen-256color-bce-s
/usr/share/terminfo/s/screen-256color-s
/usr/share/terminfo/k/konsole-256color
/usr/share/terminfo/E/Eterm-256color
/usr/share/terminfo/m/mlterm-256color
/usr/share/terminfo/m/mrxvt-256color
/usr/share/terminfo/g/gnome-256color
/usr/share/terminfo/r/rxvt-256color
/usr/share/terminfo/r/rxvt-unicode-256color
/usr/share/terminfo/d/darwin-256x96-m
/usr/share/terminfo/d/darwin-256x96
/usr/share/terminfo/v/vte-256color
/usr/share/terminfo/p/putty-256color

The one we are interested in is gnome-256color. Which for me is located just past the half way point.

**Comment by ScottSolomko** [comment]
If you do not see "gnome-256color" in your results you will have to install it. In order to that type

sudo apt-get install ncurses-term

Then re-run the find command from above and you should now see it in your results.

**Comment by ScottSolomko** [comment]
Once you have verified or installed gnome-256color, you now need to configure your terminal to use it. Copy and paste the following into your .bashrc file (towards the bottom):

if [ "$TERM" = "xterm" ] ; then
    if [ -z "$COLORTERM" ] ; then
        if [ -z "$XTERM_VERSION" ] ; then
            echo "Warning: Terminal wrongly calling itself 'xterm'."
        else
            case "$XTERM_VERSION" in
            "XTerm(256)") TERM="xterm-256color" ;;
            "XTerm(88)") TERM="xterm-88color" ;;
            "XTerm") ;;
            _)
                echo "Warning: Unrecognized XTERM_VERSION: $XTERM_VERSION"
                ;;
            esac
        fi
    else
        case "$COLORTERM" in
            gnome-terminal)
                # Those crafty Gnome folks require you to check COLORTERM,
                # but don't allow you to just *favor_ the setting over TERM.
                # Instead you need to compare it and perform some guesses
                # based upon the value. This is, perhaps, too simplistic.
                TERM="gnome-256color"
                ;;
            *)
                echo "Warning: Unrecognized COLORTERM: $COLORTERM"
                ;;
        esac
    fi
fi

**Comment by ScottSolomko** [comment]
Restart your terminal then type:
1. "tput colors". This will report how many colors your terminal is using.
2. "echo $TERM". This will tell you what terminal you are using.

You should now see that your terminal is using 256 colors (from the first command) and your terminal is now gnome-256color (from the second command)

If all went well your terminal is now configured to use 256 colors. Now we just need to configure solarized.

**Comment by helloliu** [comment]
@ScottSolomko well done!  :+1:     this is my results.
liu@liu-pc:~$ tput colors
256
liu@liu-pc:~$ echo $TERM
gnome-256color
liu@liu-pc:~$ echo $COLORTERM
gnome-terminal
liu@liu-pc:~$ 
but  the problem is not resolved :(

**Comment by ScottSolomko** [comment]
Awesome! The rest is easy, i promise!

This is what I have for my solarized configuration:

let g:solarized_termcolors=256      " color depth  
let g:solarized_termtrans=0         " 1|0 background transparent  
let g:solarized_bold=1              " 1|0 show bold fonts  
let g:solarized_italic=1            " 1|0 show italic fonts  
let g:solarized_underline=1         " 1|0 show underlines  
let g:solarized_contrast="normal"   " normal|high|low contrast  
let g:solarized_visibility="low"    " normal|high|low effect on whitespace characters

You can play around with those as you see fit.

**Comment by ScottSolomko** [comment]
Hint: once you made a change, to "see" the results instead of closing vim and restarting it you can type:

:so %

Which is short for "source the current buffer", which would be .vimrc in this case

**Comment by helloliu** [comment]
@ScottSolomko    http://173346226.smugmug.com/Other/hellowliu/i-7R6zTcZ/0/S/%E6%9C%AA%E5%91%BD%E5%90%8D-S.jpg
as you can see this is my screenshot  and I would like to ask how to change the highlight current line in vim 
I want to let it looks like in gvim  
(in my vim it's color is black  )

Thanks you very much for your answer  :+1:

**Comment by ScottSolomko** [comment]
Is your terminal's background (not vim's) a shade of blue?

**Comment by helloliu** [comment]
@ScottSolomko  yeah  I also use solarized theme  and this is my  screenshot  http://173346226.smugmug.com/Other/hellowliu/i-27Bsd73/0/S/Screenshot%20from%202012-12-04%2000%3A03%3A45-S.png

**Comment by spf13** [comment]
Scott,
Thanks for this thread. This is extremely helpful.

## 

Steve Francia
http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13

**Comment by sbennett18** [comment]
@helloliu Did you ever manage to get this issue figured out? I'm having the same issues as you with the dark background on the CursorLine.

**Comment by qiuwei** [comment]
I got

> tuput colors
> 256
> echo $TERM
> xterm-256color

But the vim in terminal still looks different and strange. I removed the config 
let g:let g:solarized_termcolors=256
Then everything is ok.

Note:
I'm using terminator, and set the palatte right according to the suggests from the author of solarized.

By the way,
Why is the autocomplete's color doesn't fit to the color theme? 
Is it a feature?

**Comment by crunchbang** [comment]
I had the same problem. I fixed it by removing the line:

let g:solarized_termcolors=256

from my .vimrc.

**Comment by barraponto** [comment]
This should be fixed by https://github.com/spf13/spf13-vim/pull/109

**Comment by barraponto** [comment]
agh, i meant introduced by.

**Comment by barraponto** [comment]
Ok, so here's what I found out, mostly thanks to [a question in superuser.com](http://superuser.com/questions/423709/vim-how-to-configure-solarized-colorscheme-in-konsole): solarized support in terminal vim comes in two flavors. The best results (as far as I can see) come from setting your terminal colors to the solarized colors — there are colorschemes for both [Konsole](https://github.com/phiggins/konsole-colors-solarized) and [Gnome Terminal](https://github.com/sigurdga/gnome-terminal-colors-solarized). Once you get your terminal emulator solarized, you have to set vim to use **16 colors**. Yes, you've read that right, I really mean SIXTEEN COLORS. You see, once your terminal colors are solarized, they're exactly what you need for a shiny gorgeous solarized vim. Adding these lines to .vimrc.local are enough:

```
let g:solarized_termcolors=16
color solarized
```

The second line, `color solarized` is required to reload the colorscheme. That's why I failed to set it back when I tried to debug https://github.com/spf13/spf13-vim/issues/113#issuecomment-10740307.

The other flavor should be useful if you don't want to solarize your terminal colors, or there's no shared colorscheme and you don't want to learn how to apply them manually. If your terminal colors are **not** solarized, then you can use the **degraded** 256-colors support. This won't be as good, but it should be good enough. See the [vim-colors-solarized notes](https://github.com/altercation/vim-colors-solarized#important-note-for-terminal-users) for more explanations.

Good news: spf13-vim already supports the degraded 256-colors solarized terminal Vim. This makes a lot of sense for a Vim distribution: you can't assume the user is using a solarized terminal. But we should make it easier to find this out and have a great solarized terminal vim experience. We should at least add it to the README.

**Comment by qiuwei** [comment]
@barraponto 

Thanks for the solution. I tried it but it doesn't make any difference.
I'm using solarized terminator.

**Comment by barraponto** [comment]
@qiuwei I've tried out ghuntley/terminator-solarized and I guess the problem lies there. With the light solarized scheme, the only issue i found on vim was that it didn't highlight the current line. With the dark colorscheme though, things got really out of hand. I'd open an issue in the terminator colorscheme repository.

**Comment by helloliu** [comment]
thankyou verymuch  i have already solved this porblem  but i also thanks
for your answer

2013/3/21 Capi Etheriel notifications@github.com

**Comment by bronzehedwick** [comment]
@helloliu, can this issue be closed?

**Comment by ghost** [comment]
closing for lack of response. reopen if you can you can reproduce with latest spf13-vim

**Comment by jeffmccune** [comment]
When the terminal has a solarized palette installed, spf13 definitely gets this wrong in the `~/.vimrc` it creates.  I fixed the solarized colors by adding the following to `~/.vimrc.local`.

```
" Fix solarized colors.  spf13 overrides the default behavior of " solarized in
" ~/.vimrc and it gets it all wrong for terminals with the solarized palette.
" Here, we set everything back to the solarized " defaults.
let g:solarized_termcolors=16
let g:solarized_termtrans=0
let g:solarized_degrade=0
let g:solarized_bold=1
let g:solarized_underline=1
let g:solarized_italic=1
let g:solarized_contrast="normal"
let g:solarized_visibility="normal"
color solarized
```

**Comment by jeffmccune** [comment]
As an update here's a fix for both the missing colors in vim-signify (The git indicators in the gutter) and vim-indent-guides.  This works well with iTerm2 with an installed solarized palette.

```
" Fix solarized colors.  spf13 overrides the default behavior of solarized in
" ~/.vimrc and it gets it all wrong for terminals with the solarized palette.
" Here, we set everything back to the solarized defaults.
let g:solarized_termcolors=16
let g:solarized_termtrans=0
let g:solarized_degrade=0
let g:solarized_bold=1
let g:solarized_underline=1
let g:solarized_italic=1
let g:solarized_contrast="normal"
let g:solarized_visibility="normal"
color solarized
" Fix indent guide colors to use solarized colors
" https://github.com/nathanaelkane/vim-indent-guides#setting-custom-indent-colors
" For 16 colors term bg colors, base03 => 8, base02 => 0, base01 => 10
let g:indent_guides_auto_colors = 0
autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  guibg=#073642 ctermbg=0
autocmd VimEnter,Colorscheme * :hi IndentGuidesEven guibg=#073642 ctermbg=0
" Fix Git indicator colors in gutter.
" See: https://github.com/mhinz/vim-signify/issues/128
autocmd VimEnter,Colorscheme * :hi SignColumn guibg=#073642  ctermbg=0
```
