### ISSUE TITLE
vimdiff "]c" jump to next diff doesn't work

### ISSUE THREAD

**Issue by yssource** [spf13/spf13-vim#320]
the "]c" originally used as a diff command, now be changed. Is it possibly to keep it work again?

**Comment by jaswani** [comment]
I too can see this issue, is there are plan to fix it?

**Comment by pandazxx** [comment]
Same issue, seems "]c" will enter visual mode and select a wired range

**Comment by keelerm84** [comment]
]c is getting re-bound by [python.vim](https://github.com/vim-scripts/python.vim)  The script is supposed to be loaded into the ftplugin directory, but it is instead being cloned into plugin, so it is being loaded automatically.  I believe the problem is that its script type is "utils" on vim.org/scripts instead of as an "ftplugin" script type, causing the github mirror to setup a suboptimal directory structure, but I'm not 100% on how that is handled.  I have emailed the author for clarification, and hopefully some resolution.  In the meantime, if you just move .vim/bundle/python.vim/plugin to .vim/bundle/python.vim/ftplugin, it should behave appropriately for you.

**Comment by bronzehedwick** [comment]
@yssource, was this issue resolved?

**Comment by jmlarson1** [comment]
Is this issue still open?

**Comment by yssource** [comment]
It was resolved. 
I feel terrible sorry, forget to close it.
