### ISSUE TITLE
Filetype detection don't work on file created by Vim

### ISSUE THREAD

**Issue by SecurityAddicted** [spf13/spf13-vim#337]
Hi!
In my spf13 install seems that vim don't recognize filetype if it creates the file.
On old file, instead, the detection work flawlessy.

**Comment by SecurityAddicted** [comment]
Seems that the problem arise only if the filename don't have any extension.

**Comment by spf13** [comment]
This is all vim, not just spf13 vim. This is because the file type is set
on buffer open and your new file doesn't have a type yet when the buffer is
created. You  either need to set the type when you create the buffer or add
an autocmd on write to redetect the type.

Steve Francia
spf13.com
@spf13

On Apr 9, 2013, at 2:40 PM, Alex-SA notifications@github.com wrote:

Hi!
In my spf13 install seems that vim don't recognize filetype if it creates
the file.
On old file, instead, the detection work flawlessy.

—
Reply to this email directly or view it on
GitHubhttps://github.com/spf13/spf13-vim/issues/337
.

**Comment by SecurityAddicted** [comment]
Thanks for the reply.
Yes, I know this behaviour of Vim. But, if I close and reopen the file, it don't detect the filetype however.

**Comment by spf13** [comment]
It caches it in the view (along with other local to that file settings)

## 

Steve Francia
http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13

**Comment by SecurityAddicted** [comment]
Disable the views don't fix the problem.

**Comment by SecurityAddicted** [comment]
EDIT: Disable the views actually fix the problem for me.
Thank you for pointing me in the right direction Steve ;-)
