### ISSUE TITLE
which font needed to use powerline?

### ISSUE THREAD

**Issue by ghost** [spf13/spf13-vim#344]
I have source code pro for powerline installed ,but still got this:
http://wstaw.org/m/2013/04/15/plasma-desktopADw828.png

Which font do I need to make it work?

**Comment by jcbwlkr** [comment]
I think the powerline fonts from the old vim-powerline project are
incompatible with the new powerline project. I could be mistaken in that
but it seems to match my experience. Try uninstalling the font and
reinstalling with the font from https://github.com/Lokaltog/powerline-fonts.

Let me know if that's not it because there are some other debugging steps
but I'm not finding them right at the moment.

**Comment by ghost** [comment]
I did that and I edit .vimrc with GUI part,gvim's powerline works,but I set pixsize to 14,the text font size is good,while powerline's text is larger that it should be.
But I mainly use vim in urxvt,I change it's default font to Dejavu Sans Mono for Powerline but it seem doesn't work.

**Comment by Gaelan** [comment]
I don't use urxvt, but I wonder if "default" means a) it only applies to new sessions, or b) something else is overriding it.
