### ISSUE TITLE
Vim asks me "Press Enter or type command to continue" at startup.

### ISSUE THREAD

**Issue by xu-cheng** [spf13/spf13-vim#540]
Every time I open vim, it will ask me "Press Enter or type command to continue" which it's extremely annoying. For example, if I open vim using `vim test.txt`, it will show as below:
![Imgur](http://i.imgur.com/bG8E722.png)

**Comment by ljani** [comment]
Can you try typing `:messages` to see if there were some errors or something? Additionally clearing `~/.vimviews` solves many problems if you have done configuration changes.

**Comment by xu-cheng** [comment]
Clearing `~/.vimviews` has nothing changed. Typing :messages only show `Messages maintainer: Bram Moolenaar <Bram@vim.org>`. BTW my vim and spf13-vim is a fresh install without any configuration.

-- 
Xu Cheng

开启 2014年1月30日 at 下午1:33:06, Jani (notifications@github.com) 写:

Can you try typing :messages to see if there were some errors or something? Additionally clearing ~/.vimviews solves many problems if you have done configuration changes.

**Comment by natec8** [comment]
I get this same problem, clearing ~/.vimviews didn't work for me either. I am on OS X 10.9.1 and just installed spf13 yesterday.

**Comment by tvanhens** [comment]
Having the same issue as well although I also get a neosnippets error when I type :messages. Was a fresh install

**Comment by chaptastic** [comment]
This seems to occur with the system vim on 10.9.1. I was seeing the same thing but it stopped happening when I switched to macvim installed via homebrew.

**Comment by xu-cheng** [comment]
Yeah, I can now confirm that it only occurs with system vim 7.3. Installing latest vim and macvim via homebrew solves the problem. Close the issue.

**Comment by motyar** [comment]
Put these two lines in .vimrc

set shortmess=a
set cmdheight=2

**Comment by aubreypwd** [comment]
Same issue. Using vim in iTerm2. `brew install vim` did not fix the issue. Note, I now have vim 7.4 and it's still happening. Also happens in Terminal.app

**Comment by aubreypwd** [comment]
Why is the startup output showing the filename twice? `1:.vimrc.local`

**Comment by carlotrimarchi** [comment]
It's still happening to me on Macvim installed via homebrew on a Mac 10.9

**Comment by felix-d** [comment]
The issue was happening only in the terminal for me, using `vim` command.
I was running the vim version bundled with OSX, the one located at `/usr/bin/vim` which was version 7.3.

I corrected the issue by reinstalling macvim for version 7.4 via homebrew
**AND**
I moved `/usr/bin/vim` to `/usr/bin/vim.deprecated` and created an alias in my zsh profile:

`alias vim="/usr/local/bin/mvim -v"`

Or you could have simply used

`brew install macvim --override-system-vim`

to override `vim` command.

_ps. I used spf13 too_

**Comment by yuhailei1992** [comment]
installed vim 7.4 from source code, and used 'alias' to make vim 7.4 default. Problem solved

**Comment by Qix-** [comment]
As @motyar [suggested](https://github.com/spf13/spf13-vim/issues/540#issuecomment-37716820)

``` viml
set shortmess=a
```

in `~/.vimrc` worked for me!

**Comment by ks--ks** [comment]
try https://github.com/spf13/spf13-vim/issues/662#issuecomment-58359451

``` sh
echo 'let g:bufferline_echo=0' >>  ~/.vimrc.local
```

**Comment by gricha** [comment]
I also had this issue, but I didn't need to edit my .vimrc, it just turned out I had installed 7.4, but my PATH was still redirecting to 7.3. Following http://www.prioritized.net/blog/upgrading-vim-on-os-x/ fixed it for me.

**Comment by ghost** [comment]
I think we should probably error out if we detect a vim that isn't at least 7.4

**Comment by lewison** [comment]
vim ~/.vimrc.local 
and set:

set shortmess=a
set cmdheight=2

fixed my problem. thx for your help.

**Comment by lymanlai** [comment]
@lewison https://github.com/spf13/spf13-vim/issues/540#issuecomment-101488443  this also work for me

**Comment by marcusmolchany** [comment]
Thanks @motyar, set shortmess=a fixed it

**Comment by seanchen** [comment]
I got the issue when my disk space was full. As long as I freed some disk space, it is back to normal.

**Comment by dora-gt** [comment]
commented out "set syntax" in .vimrc
that worked for me

**Comment by hounded** [comment]
change the following worked for me in .vimrc
```bash 
set syntax
```
To
```bash 
syntax on
```

**Comment by alphaCTzo7G** [comment]
Setting `set shortmess=a` solved it for me. I starting having this problem in Vim8 when I tried increasing the number of lines in each register with `set viminfo`

**Comment by IvanSlaev** [comment]
It is invoked by an error, e.g. in my case there was no dir where it was set to store swap files. So sometimes it shows the 403 error that no swap was found, but sometimes it didn't and I was wondering why it asks me to press enter or... So before "hacking" with some set shortmess or something just check the .vimrc for mistakes and explore the error messages.

**Comment by soerenwolfers** [comment]
In case you don't like increased command line space, try `set shortmess=at`. I found the `t` in `:h shortmess`

**Comment by oyc502** [comment]
> Put these two lines in .vimrc
> 
> set shortmess=a
> set cmdheight=2

it doesn't work

**Comment by Johnson-Lease** [comment]
A syntax in .vimrc is incomplete. There is no value to 'syntax'.
In .vimrc it looked like this:
`set syntax`

Change it to:
`set syntax=on`
Problem solved.

**Comment by kjsf** [comment]
there is a syntax error on the vimrc file, finding it would remove this.

**Comment by kasumiru** [comment]
Have a same bug! 
cat ~/.vimrc

set syntax=on
color darkblue
set mouse -=a
set shortmess=a
set cmdheight=2

**Comment by egrubbs** [comment]
https://unix.stackexchange.com/a/480138 explains how to disable the focus events.

Some apps will turn on the focus events, and if the process dies, the events won't get turned off. If your terminal does not have the focus events turned on by default, you can go back to the defaults by running:
```
reset
```

**Comment by jurelik** [comment]
In my case, the problem was caused by vim echoing a long cwd file path on first open. To fix that you need to enable the F flag in your shortmess setting to prevent Vim from echoing the current filename into the command line.

`set shortmess=F`

Source: https://vi.stackexchange.com/questions/17723/how-to-disable-displaying-of-filename-in-the-command-bar-when-opening-files-in-v

**Comment by jakjus** [comment]
It started happening for me on MacOS, when I have shrinked the Neovim terminal window. Interesting. 

Enlarging the window OR applying motyar's commands (below) fixes the issue for me.

> Put these two lines in .vimrc
> 
> set shortmess=a set cmdheight=2

**Comment by TomasTillmann** [comment]
Unfortunately, neither `set shortmess=a`, `set shortmess=at`, `set shortmess=F` or removing or clearing `.vimviews` dind't work for me.

I'm using windows terminal on windows 11.

After writing `vim whateverfile.txt` in the terminal, this window shows up.
![image](https://github.com/spf13/spf13-vim/assets/82380952/67df3d83-2ca8-4691-b2a4-ee2479d718ce)

After pressing any key, vim than works perfectly fine. But pressing enter all the time is getting little bit frustrating. It wasn't happening until I started editing my _vimrc file in C:\Users\<me>\. 

I also tried to clear my _vimrc but it was still happing. Also reseted the session in between.

It seems to be a vim issue, since in different terminal it is also the case.

This is alacritty:
![image](https://github.com/spf13/spf13-vim/assets/82380952/0b253274-b01b-40c4-b80d-3bfaf90d86ae)

Anyone having the same issue? Thanks.
