### ISSUE TITLE
Doesn't Respect Tab Settings in .vimrc.local or .vimrc.before.local

### ISSUE THREAD

**Issue by program247365** [spf13/spf13-vim#589]
Tried this single line in my .vimrc.local or .vimrc.before.local

```
set tabstop=4 softtabstop=4 shiftwidth=4 noexpandtab
```

And get mixed results, as if some files I open (.less) files don't honor it, and then other files I open (.json, or .bower) do honor it. New files will honor the tab settings, but not some existing files.

I also did this:

```
chmod 777 ~/.vimrc.local
```

Thinking it perhaps couldn't read it, and that didn't really help.

Anyone else experience this?

**Comment by spf13** [comment]
Some of the different language plugins set this after the .vimrc (local and before) is sourced.

It’s also possible that vim views have cached your previous session for that file. Try clearing your ~/.vimviews directory.

Best,
Steve

-- 
Steve Francia
http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13

**Comment by program247365** [comment]
```
rm -rf ~/.vmviews/*
```

That seemed to do the trick. Thanks!

**Comment by aubreypwd** [comment]
Clearing `.vimviews` did not work when editing a `.php` file.

**Comment by CodisRedding** [comment]
I'm having the same issue. I've purged all the views but I'm still not able to lint my js, and coffee files. Could this be an issue pertaining to the file types? I keep getting "Expected 2 got 4" which makes sense since all my tabs are 4 spaces even though I want 2.

[~/.vimrc](http://pastebin.com/XFdiG8Yd)
[~/.vimrc.local](http://pastebin.com/xAdxYKAG)
