### ISSUE TITLE
Needs additional info on README

### ISSUE THREAD

**Issue by cr8ivecodesmith** [spf13/spf13-vim#77]
I think it would be useful to add whether to install this over an existing vim installation  
or should we uninstall the current one and replace it with this one.

**Comment by taxilian** [comment]
This doesn't replace your vim installation, but it does completely replace your vim scripts and customizations.

Hard to do a solid README for this, I'd think, but you basically just move your existing scripts out of the way (which bootstrap does by default) and install this in its place.

I don't think a README entry is needed simply because the default behavior does what the README would tell you to do -- backs up the old config, installs spf13-vim
