### ISSUE TITLE
Neocomplete invasively changes behavior of Enter and Esc keys

### ISSUE THREAD

**Issue by Slotos** [spf13/spf13-vim#796]
Background: Debian Jessie, stock vim, fresh install under new user, multiple separate systems. I haven't tested extensively for whether it's spf13 integration fault or inherent neocomplete problem though.

When neocomplete encounters a line, that has snippets available, instead of silently nooping on <CR>, it inserts "<Plug>(neosnippet_expand)" string instead.

In addition to that, when there is a neocomplete popup present, <Esc> key behaviour gets modified: instead of returning vim to normal mode, it returns vim to normal mode and activates insert mode with a brief delay, reactivating popup. Depending on connection speed sometimes it means that it's impossible to exit said popup prompt without killing vim.

**Comment by tchar** [comment]
I am having a somewhat relevant problem, so I am not opening a new issue.

First of all when I type and a snippet is available (lets say main for a c file), I get the popup but when I hit tab and enter I get: 
main<Plug>(neosnippet_expand) as Slotos described

Of course if I hit Control + K I get the proper snippet and the (main) autocomplete works.
Have you tried hitting C - k instead of enter?

Secondly, I am having another problem with autocomplete.
When I type something and a suggestion pops (not a snippet), the autocomplete should work as:
Hit tab and enter and the word will autocomplete.
When I hit tab I get the word autocomplete, as it should, but when I hit enter to choose the proper autocomplete, vim gets me back to the word as I wrote it before the autocomplete popped (as if nothing happened).

For example:
I open .vimrc.local and I write: "colorscheme twili"
and now opens the autocomplete popup, I hit two tabs to get "twilight256" so now vim has:
"colorscheme twilight256"
Then I hit enter and now vim has:
"colorscheme twili"

I got it to wok by hitting tab, writing a letter and then hitting backspace, but it gets disturbing.

Any suggestions especially for the second issue?

I am running 4.0.5-1-ARCH linux 64 bit, with gnome 3 and vim 7.4

**Comment by bmenant** [comment]
Having the same issue since I update spf13 and bundles.
Probably related to https://github.com/spf13/spf13-vim/issues/775 and https://github.com/Shougo/neocomplete.vim/issues/347

**Comment by rodfersou** [comment]
I think this configuration from [vim multiplecursors page](https://github.com/kristijanhusak/vim-multiple-cursors#multiple_cursors_beforemultiple_cursors_after-default-nothing) should go into spf13 default configuration (this solved the problem for me):

```
" Called once right before you start selecting multiple cursors
function! Multiple_cursors_before()
  if exists(':NeoCompleteLock')==2
    exe 'NeoCompleteLock'
  endif
endfunction

" Called once only when the multiple selection is canceled (default <Esc>)
function! Multiple_cursors_after()
  if exists(':NeoCompleteUnlock')==2
    exe 'NeoCompleteUnlock'
  endif
endfunction
```

**Comment by FiloSpaTeam** [comment]
Try my configuration of NeoComplete, in my fork ;-)

**Comment by rodfersou** [comment]
@FiloSpaTeam could you point me where is it?

**Comment by insanemal** [comment]
I too am having the issue that tchar is having. It's literally the most frustrating thing at the moment.

**Comment by btzo** [comment]
Any updates on this issue? I'm having the same problem pointed by @tchar.
@FiloSpaTeam I looked in your github repository and didn't find your fork =/
@rodfersou you can give me more details of how you solved this problem by using the  multiplecursors snippet code ?
