### ISSUE TITLE
pumvisible problem with perl (*.pl) files

### ISSUE THREAD

**Issue by djehauti** [spf13/spf13-vim#84]
every time I hit enter I get this:

pumvisible() ? neocomplcache#close_popup() : "\
   "" 

when editing a file that ends with .pl

I believe this is from line 498 in the vimrc:

```
 inoremap <expr><CR>  pumvisible() ? neocomplcache#close_popup() : "\<CR>"
```

which is in the fugitive section, the weird thing is this does not affect any other file types that I have tried (php, config files, etc).  Scratch that it affects python files as well, any clue how I can fix this?

**Comment by taxilian** [comment]
this issue is linked to snipmate; make sure you've updated to the latest, etc, and then try deleting your ~/.vimviews directory. Usually I've seen this issue because something changed in snipmate and the vimviews caused the old stuff to persist in certain cases.

Deleting the ~/.vimviews files fixed it for me. If that doesn't fix it for you, try switching to just use neocomplcache and disable snipmate, clean your bundles, and then delete the vimviews again.  That should do it.
