### ISSUE TITLE
Broken installation script

### ISSUE THREAD

**Issue by LuisAlejandro** [spf13/spf13-vim#929]
Apparently there has been a change on the default branch which has broken the installation script.

This line https://github.com/spf13/spf13-vim/blob/master/bootstrap.sh#L20 clones the repo without a branch argument, which clones the default (3.0) that does not have the .vim folder.

I'll be providing a PR soon.

**Comment by LuisAlejandro** [comment]
@spf13 quick but fatal bug here.

**Comment by ghost** [comment]
@LuisAlejandro : the last commit to master was in 2014. Using 3.0 is intended. If there's a bug, it isn't that.

**Comment by LuisAlejandro** [comment]
@jrobeson 

Well, i guess it was a false positive, somehow the URL shortener redirected me to:

https://github.com/spf13/spf13-vim/blob/master/bootstrap.sh

instead of:

https://github.com/spf13/spf13-vim/blob/3.0/bootstrap.sh

Which will fail because of what i explained. You should change the script anyway because someone installing from master will get a failed installation, don't you think?

**Comment by ghost** [comment]
change it to ? master? no.

**Comment by ghost** [comment]
I've contacted @spf13 to see if he can look into the url shortener issue you're seeing.

**Comment by LuisAlejandro** [comment]
@jrobeson 
Change it to master in master? makes no sense?
:-(

**Comment by ghost** [comment]
i'd rather it fail completely than allow people to install the master branch. seems like it might be better to adapt the installer to just error out on fresh installs. It could say something like "You're installing an unmaintained version of spf-13, please check out 3.0 branch and run the bootstrap script"

We can't let them use the bootstrap script from master to install 3.0, since it won't work correctly.

**Comment by LuisAlejandro** [comment]
Closing this, as apparently not a bug.
